spring:
  application:
    name: progress-tracker
  datasource:
    url: jdbc:h2:file:./data/progressdb        # stores data in ./data/progressdb.mv.db
    driver-class-name: org.h2.Driver
    username: sa                                # H2 default user
    password:                                    # empty by default
  jpa:
    hibernate:
      ddl-auto: update                          # create / migrate tables automatically
  h2:
    console:
      enabled: true
      path: /h2-console
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    com:
      progressTracker: DEBUG
  pattern:
    console: "%-5level - %replace(%msg){'[\\r\\n]', ''}%n"

server:
  error:
    include-stacktrace: never
    include-message: always