# .github/workflows/pr-check.yml
name: PR Check

on:
    pull_request:
        branches: [main] # or whatever branch is protected

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Fetch code
            - uses: actions/checkout@v4

            # Set up JDK 21 (Temurin)
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: gradle # speeds up subsequent runs

            # Style-check ONLY (fails fast if lint errors)
            - name: Run Checkstyle
              run: |
                  ./gradlew checkstyleMain checkstyleTest --no-daemon
              # always show the HTML reports even on failure
              continue-on-error: true

            # Build, unit-test, Jacoco
            - name: Build & test
              run: ./gradlew clean build --no-daemon

            # Upload test reports
            - name: Upload unit-test reports
              if: always() # run even if tests failed
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: build/reports/tests/

            # Upload Checkstyle HTML reports
            - name: Upload Checkstyle reports
              if: always()
              uses: actions/upload-artifact@v4
              with:
                  name: checkstyle-reports
                  path: |
                      build/reports/checkstyle/main.html
                      build/reports/checkstyle/test.html

            # code-coverage summary in the PR conversation
            - name: Code coverage summary
              if: success() # only if build + tests passed
              run: |
                  ./gradlew jacocoTestReport --no-daemon
                  echo "### Code coverage" >> $GITHUB_STEP_SUMMARY
                  awk -F'"' 'NR==2 { total=$6+$8; cov=(total==0?0:$6*100/total); printf("%.2f%%\n", cov) }' \
                      build/reports/jacoco/test/jacocoTestReport.xml >> $GITHUB_STEP_SUMMARY
