# .github/workflows/pr-check.yml
name: PR Check

on:
    pull_request: # run on every push to an open PR
        branches: [main] # …or whatever branch is protected

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            # Get the code
            - uses: actions/checkout@v4

            # Set up Java (Temurin = AdoptOpenJDK)
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: gradle # tiny flag → automatic ~/.gradle cache

            # Clean + Build + Test
            - name: Build & test
              run: ./gradlew clean build --no-daemon

            # Publish the results (so they show up in the PR UI)
            - name: Upload test reports
              if: always() # run even if tests failed
              uses: actions/upload-artifact@v4
              with:
                  name: test-results
                  path: build/reports/tests/

            # (Optional) JaCoCo coverage summary in PR
            - name: Code coverage summary
              if: success() # only if tests passed
              run: |
                  mkdir -p target/site/jacoco   # convert location if you use Maven
                  ./gradlew jacocoTestReport
                  echo "### Code coverage" >> $GITHUB_STEP_SUMMARY
                  grep -A1 '<counter type="INSTRUCTION"' build/reports/jacoco/test/jacocoTestReport.xml \
                  | tail -1 \
                  | awk -F'"' '{printf("%s%%\n", $6*100/($6+$8))}' \
                  >> $GITHUB_STEP_SUMMARY
