# .github/workflows/pr-check.yml
permissions:
  contents: read # for checkout/build
  issues: write # to call the issues API
  pull-requests: write # to call the pull_requests API

name: PR Check

on:
  pull_request:
    branches: [main] # adapt if you use a different default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Fetch code ──────────────────────────────────────────────────────────
      - uses: actions/checkout@v4

      # 2) JDK 21 + Gradle cache (Temurin) ─────────────────────────────────────
      - uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: gradle # <-- re-uses ~/.gradle caches between runs

      # 3) Lint first – but *capture* the exit code so the job can still finish
      - name: Run Checkstyle
        id: checkstyle # we’ll look at this id later
        shell: bash
        run: |
          set +e                       # (1) don’t abort the shell immediately
          ./gradlew --no-daemon \
              checkstyleMain checkstyleTest
          echo "checkstyle_exit=$?" >> "$GITHUB_OUTPUT"

      # 4) Build, unit-test, Jacoco  ───────────────────────────────────────────
      - name: Build & test
        run: ./gradlew clean build --no-daemon

      # 5) Always upload unit-test xml/html ⇢ PR Artifacts
      - name: Upload unit-test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/reports/tests/

      # 6) Always upload Checkstyle reports (html + xml)
      - name: Upload Checkstyle reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: |
            build/reports/checkstyle/*.html
            build/reports/checkstyle/*.xml

      # 7) Generate coverage and capture it
      - name: Generate coverage and capture it
        id: coverage
        shell: bash
        run: |
          ./gradlew jacocoTestReport --no-daemon

          # --- parse JaCoCo XML with tiny Python ---
          COVERAGE=$(python - <<'PY'
          import xml.etree.ElementTree as ET
          root = ET.parse('build/reports/jacoco/test/jacocoTestReport.xml').getroot()
          counter = next(c for c in root.iter('counter') if c.get('type') == 'LINE')
          missed, covered = int(counter['missed']), int(counter['covered'])
          total = missed + covered
          print(f'{0.0 if total == 0 else covered * 100 / total:.2f}')
          PY
                    )

          echo "coverage=${COVERAGE}" >> "$GITHUB_OUTPUT"
          echo "### Code coverage: ${COVERAGE}%" >> "$GITHUB_STEP_SUMMARY"



      # 8) Post that coverage as a PR comment
      - name: Post code-coverage to PR
        if: success()
        uses: peter-evans/create-or-update-comment@v4
        with:
          token:        ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          marker:       <!-- code-coverage-comment -->
          body: |
            <!-- code-coverage-comment -->
            🧪 **Code Coverage**  
            Current code coverage is **${{ steps.coverage.outputs.coverage }}%**.

      # 9) Finally, **fail the job** if Checkstyle produced any violations
      - name: Fail if Checkstyle failed
        if: steps.checkstyle.outputs.checkstyle_exit != '0'
        run: |
          echo "Checkstyle violations detected – see the uploaded HTML report." >&2
          exit 1
